# Generated by Django 3.0.5 on 2020-04-12 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('branch_name', models.CharField(max_length=30)),
                ('street_line_1', models.CharField(max_length=50)),
                ('street_line_2', models.CharField(max_length=35)),
                ('city', models.CharField(max_length=45)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.CharField(max_length=10)),
                ('comments', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(verbose_name='last updated')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('datetime_submitted', models.DateTimeField(verbose_name='datetime submitted')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locator.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locator.Location')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locator.Rating')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='services',
            field=models.ManyToManyField(to='locator.Service'),
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='locator.Service')),
            ],
        ),
    ]
