# Generated by Django 3.0.5 on 2020-04-12 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='ServiceTimeRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('start_time', models.TimeField(verbose_name='time start')),
                ('end_time', models.TimeField(verbose_name='time end')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locator.Location')),
            ],
        ),
        migrations.CreateModel(
            name='DayTimeRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=3)),
                ('open_time', models.TimeField(verbose_name='time open')),
                ('close_time', models.TimeField(verbose_name='time closed')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locator.Location')),
            ],
        ),
    ]
