# Generated by Django 3.0.5 on 2020-04-12 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0002_auto_20200412_0008'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categories',
            new_name='ServiceCategories',
        ),
    ]
