# Generated by Django 3.0.5 on 2020-04-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0004_auto_20200412_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecategory',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
