# Generated by Django 3.0.5 on 2020-04-12 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0007_auto_20200412_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='fax',
            field=models.CharField(default='', max_length=14),
        ),
        migrations.AddField(
            model_name='location',
            name='phone',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=320, null=True)),
                ('phone', models.CharField(blank=True, max_length=25, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locator.Location')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='auth_catogory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locator.AuthCategory'),
        ),
    ]
