# Generated by Django 3.0.5 on 2020-04-12 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0009_ccfcategory_drugscreenauthcategory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DrugScreenAuthCategory',
            new_name='DrugScreenMethod',
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'verbose_name': 'Service Category', 'verbose_name_plural': 'Service Categories'},
        ),
        migrations.RenameField(
            model_name='location',
            old_name='services',
            new_name='service_list',
        ),
        migrations.AddField(
            model_name='location',
            name='ds_auth_list',
            field=models.ManyToManyField(to='locator.DrugScreenMethod'),
        ),
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locator.Location')),
            ],
        ),
    ]
