# Generated by Django 3.0.5 on 2020-04-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0010_auto_20200412_0345'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthCategory',
            new_name='AuthMethod',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='ds_auth_list',
            new_name='ds_method_list',
        ),
        migrations.RemoveField(
            model_name='location',
            name='auth_catogory',
        ),
        migrations.AddField(
            model_name='location',
            name='auth_method_list',
            field=models.ManyToManyField(to='locator.AuthMethod'),
        ),
    ]
