# Generated by Django 3.0.5 on 2020-04-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0014_auto_20200417_0025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authmethod',
            options={'verbose_name': 'Authorization Method', 'verbose_name_plural': 'Authorization Methods'},
        ),
        migrations.AlterModelOptions(
            name='ccfcategory',
            options={'verbose_name': 'CCF Category', 'verbose_name_plural': 'CCF Categories'},
        ),
        migrations.AlterModelOptions(
            name='locationcategory',
            options={'verbose_name': 'Location Category', 'verbose_name_plural': 'Location Categories'},
        ),
        migrations.RemoveField(
            model_name='location',
            name='ds_method_list',
        ),
        migrations.AddField(
            model_name='location',
            name='ccf_category_list',
            field=models.ManyToManyField(to='locator.CcfCategory'),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(choices=[('AL', 'AL'), ('AK', 'AK'), ('AR', 'AR'), ('AZ', 'AZ'), ('CA', 'CA'), ('CO', 'CO'), ('CT', 'CT'), ('DC', 'DC'), ('DE', 'DE'), ('FL', 'FL'), ('GA', 'GA'), ('HI', 'HI'), ('IA', 'IA'), ('ID', 'ID'), ('IL', 'IL'), ('IN', 'IN'), ('KS', 'KS'), ('KY', 'KY'), ('LA', 'LA'), ('MA', 'MA'), ('MD', 'MD'), ('ME', 'ME'), ('MI', 'MI'), ('MN', 'MN'), ('MO', 'MO'), ('MS', 'MS'), ('MT', 'MT'), ('NC', 'NC'), ('NE', 'NE'), ('NH', 'NH'), ('NJ', 'NJ'), ('NM', 'NM'), ('NV', 'NV'), ('NY', 'NY'), ('ND', 'ND'), ('OH', 'OH'), ('OK', 'OK'), ('OR', 'OR'), ('PA', 'PA'), ('RI', 'RI'), ('SC', 'SC'), ('SD', 'SD'), ('TN', 'TN'), ('TX', 'TX'), ('UT', 'UT'), ('VT', 'VT'), ('VA', 'VA'), ('WA', 'WA'), ('WI', 'WI'), ('WV', 'WV'), ('WY', 'WY')], default='CA', max_length=2),
        ),
        migrations.DeleteModel(
            name='DrugScreenMethod',
        ),
    ]
