# Generated by Django 3.0.5 on 2020-04-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0016_auto_20200417_1344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daytimerange',
            options={'verbose_name': 'Day/Time Range', 'verbose_name_plural': 'Day/Time Ranges'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='servicetimerange',
            options={'verbose_name': 'Service Time Range', 'verbose_name_plural': 'Service Time Ranges'},
        ),
        migrations.AlterField(
            model_name='location',
            name='branch_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='service_list',
            field=models.ManyToManyField(to='locator.Service', verbose_name='Service List'),
        ),
        migrations.AlterField(
            model_name='location',
            name='street_line_2',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='website',
            field=models.TextField(blank=True, null=True),
        ),
    ]
