# Generated by Django 3.0.5 on 2020-04-18 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0018_auto_20200417_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authmethod',
            options={'ordering': ['name'], 'verbose_name': 'Authorization Method', 'verbose_name_plural': 'Authorization Methods'},
        ),
        migrations.AlterModelOptions(
            name='ccfcategory',
            options={'ordering': ['name'], 'verbose_name': 'CCF Category', 'verbose_name_plural': 'CCF Categories'},
        ),
        migrations.AddField(
            model_name='location',
            name='is_phone_callable',
            field=models.BooleanField(blank=True, default=True, verbose_name='Is this number callable?'),
        ),
        migrations.AlterField(
            model_name='location',
            name='fax',
            field=models.CharField(blank=True, default='', max_length=14, null=True),
        ),
    ]
