# Generated by Django 3.0.5 on 2020-04-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0019_auto_20200417_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='datetime_submitted',
        ),
        migrations.AddField(
            model_name='location',
            name='last_verified',
            field=models.DateField(blank=True, null=True, verbose_name='Last Verified'),
        ),
        migrations.AddField(
            model_name='rating',
            name='date_submitted',
            field=models.DateField(default='1900-01-01', verbose_name='Date Submitted'),
        ),
        migrations.AlterField(
            model_name='location',
            name='last_updated',
            field=models.DateField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='location',
            name='service_list',
            field=models.ManyToManyField(to='locator.Service', verbose_name='Services Offered'),
        ),
    ]
