# Generated by Django 3.0.5 on 2020-04-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0020_auto_20200417_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='rating',
            new_name='down_votes',
        ),
        migrations.AddField(
            model_name='rating',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
    ]
