# Generated by Django 3.0.5 on 2020-04-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0022_auto_20200418_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytimerange',
            name='start_hour',
            field=models.CharField(choices=[('', ''), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='', max_length=2, verbose_name='Starting Hour'),
        ),
        migrations.AlterField(
            model_name='daytimerange',
            name='end_am_pm',
            field=models.CharField(choices=[('', ''), ('AM', 'AM'), ('PM', 'PM')], default='', max_length=2, verbose_name='Ending AM/PM'),
        ),
        migrations.AlterField(
            model_name='daytimerange',
            name='end_hour',
            field=models.CharField(choices=[('', ''), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='', max_length=2, verbose_name='Ending Hour'),
        ),
        migrations.AlterField(
            model_name='daytimerange',
            name='end_min',
            field=models.CharField(choices=[('', ''), ('0', '00'), ('1', '01'), ('2', '02'), ('3', '03'), ('4', '04'), ('5', '05'), ('6', '06'), ('7', '07'), ('0', '08'), ('9', '09'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('32', '32'), ('33', '33'), ('34', '34'), ('35', '35'), ('36', '36'), ('37', '37'), ('38', '38'), ('39', '39'), ('40', '40'), ('41', '41'), ('42', '42'), ('43', '43'), ('44', '44'), ('45', '45'), ('46', '46'), ('47', '47'), ('48', '48'), ('49', '49'), ('50', '50'), ('51', '51'), ('52', '52'), ('53', '53'), ('54', '54'), ('55', '55'), ('56', '56'), ('57', '57'), ('58', '58'), ('59', '59')], default='', max_length=2, verbose_name='Ending Minute'),
        ),
        migrations.AlterField(
            model_name='daytimerange',
            name='start_am_pm',
            field=models.CharField(choices=[('', ''), ('AM', 'AM'), ('PM', 'PM')], default='', max_length=2, verbose_name='Starting AM/PM'),
        ),
    ]
