# Generated by Django 3.0.5 on 2020-04-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0025_auto_20200419_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='simple_name',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Simple Name'),
        ),
    ]
