# Generated by Django 3.0.5 on 2020-04-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0027_auto_20200430_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daytimerange',
            name='end_am_pm',
        ),
        migrations.RemoveField(
            model_name='daytimerange',
            name='end_hour',
        ),
        migrations.RemoveField(
            model_name='daytimerange',
            name='end_min',
        ),
        migrations.RemoveField(
            model_name='daytimerange',
            name='start_am_pm',
        ),
        migrations.RemoveField(
            model_name='daytimerange',
            name='start_hour',
        ),
        migrations.RemoveField(
            model_name='daytimerange',
            name='start_min',
        ),
        migrations.RemoveField(
            model_name='servicetimerange',
            name='end_am_pm',
        ),
        migrations.RemoveField(
            model_name='servicetimerange',
            name='end_hour',
        ),
        migrations.RemoveField(
            model_name='servicetimerange',
            name='end_min',
        ),
        migrations.RemoveField(
            model_name='servicetimerange',
            name='start_am_pm',
        ),
        migrations.RemoveField(
            model_name='servicetimerange',
            name='start_hour',
        ),
        migrations.RemoveField(
            model_name='servicetimerange',
            name='start_min',
        ),
        migrations.AlterField(
            model_name='daytimerange',
            name='end_time',
            field=models.TimeField(default='0:00 AM', verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='daytimerange',
            name='start_time',
            field=models.TimeField(default='0:00 AM', verbose_name='Start Time'),
        ),
        migrations.AlterField(
            model_name='servicetimerange',
            name='end_time',
            field=models.TimeField(default='0:00 AM', verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='servicetimerange',
            name='start_time',
            field=models.TimeField(default='0:00 AM', verbose_name='Start Time'),
        ),
    ]
