# Generated by Django 3.0.5 on 2020-05-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0028_auto_20200430_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='is_phone_callable',
            field=models.BooleanField(blank=True, default=True, verbose_name='Is this phone number callable?'),
        ),
    ]
