# Generated by Django 3.0.6 on 2020-05-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0029_auto_20200501_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='down_votes',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='up_votes',
        ),
        migrations.AddField(
            model_name='rating',
            name='date_edited',
            field=models.DateField(auto_now=True, verbose_name='Last Edited'),
        ),
        migrations.AddField(
            model_name='rating',
            name='dislike',
            field=models.BooleanField(default=False, verbose_name='No'),
        ),
        migrations.AddField(
            model_name='rating',
            name='like',
            field=models.BooleanField(default=False, verbose_name='Yes'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='date_submitted',
            field=models.DateField(auto_now_add=True, verbose_name='Date Submitted'),
        ),
    ]
