# Generated by Django 3.0.6 on 2020-05-09 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0034_auto_20200507_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['service_category', 'name']},
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='service',
            name='simple_description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
