# Generated by Django 3.0.6 on 2020-05-09 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0036_auto_20200509_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetimerange',
            options={'ordering': ['name'], 'verbose_name': 'Service Time Range', 'verbose_name_plural': 'Service Time Ranges'},
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='simple_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
