# Generated by Django 3.0.6 on 2020-05-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0037_auto_20200509_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytimerange',
            name='day',
            field=models.IntegerField(choices=[('', ''), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], default=1),
        ),
    ]
