# Generated by Django 3.0.6 on 2020-05-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0038_auto_20200514_2244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daytimerange',
            options={'ordering': ['day'], 'verbose_name': 'Day/Time Range', 'verbose_name_plural': 'Day/Time Ranges'},
        ),
        migrations.AddConstraint(
            model_name='daytimerange',
            constraint=models.UniqueConstraint(fields=('location', 'day'), name='daytimerange_location_day_key'),
        ),
    ]
