# Generated by Django 3.0.6 on 2020-05-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0039_auto_20200514_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
