# Generated by Django 3.0.6 on 2020-06-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0040_auto_20200514_2349'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='location',
            name='location_name_branch_name_key',
        ),
        migrations.AlterField(
            model_name='location',
            name='last_verified',
            field=models.DateField(auto_now=True, null=True, verbose_name='Last Verified'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('name', 'branch_name', 'street_line_1'), name='location_name_branch_name_street_line_1_key'),
        ),
    ]
