# Generated by Django 3.0.8 on 2020-08-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0041_auto_20200621_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='simple_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Simple Name'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('service_category', 'name'), name='service_service_category_name_key'),
        ),
    ]
