# Generated by Django 3.0.8 on 2020-08-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0046_auto_20200805_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9, unique=True)),
                ('abbreviation', models.CharField(max_length=3, unique=True)),
            ],
        ),
    ]
