# Generated by Django 3.0.8 on 2020-08-05 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0047_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daytimerange',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locator.Day'),
        ),
    ]
