# Generated by Django 3.0.8 on 2020-08-05 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0049_servicetimerange_days'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
