# Generated by Django 3.0.8 on 2020-08-06 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0051_auto_20200805_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='last_verified',
            new_name='last_updated',
        ),
    ]
