# Generated by Django 3.0.8 on 2020-08-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0052_auto_20200805_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='last_updated',
            field=models.DateField(auto_now=True, null=True, verbose_name='Last Updated'),
        ),
    ]
