# Generated by Django 3.0.8 on 2020-08-06 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0053_auto_20200805_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='author',
            new_name='owner',
        ),
    ]
