# Generated by Django 3.1 on 2020-08-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0056_auto_20200814_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='phone',
            field=models.CharField(default='', max_length=28),
        ),
    ]
