# Generated by Django 3.1.1 on 2020-10-03 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0059_locationcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationcomment',
            options={'verbose_name': 'Location Comment'},
        ),
        migrations.AddField(
            model_name='locationcomment',
            name='comment',
            field=models.TextField(default='', verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='locationcomment',
            name='date_edited',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='locationcomment',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
