# Generated by Django 3.1.1 on 2020-10-06 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0060_auto_20201003_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationcomment',
            old_name='owner',
            new_name='author',
        ),
    ]
