# Generated by Django 3.1.1 on 2020-10-18 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0061_auto_20201005_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetimerange',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locator.servicecategory'),
        ),
    ]
